// assembly/codegen.ts
import { Node } from "./ast";

export function generatePBASIC(_tree: Node): string {
  // Placeholder code generator - NOT FINALIZED
  return [
    "' IZEBOT.BSP",
    "' Generated by pseudo-compiler",
    'DEBUG "Hello IZEBOT"',
    "END",
  ].join("\n");
}
